name: Bug Report
description: Create a report to help us improve the overlay
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Please provide as much detail as possible. Remember we only support Windows and macOS.
  - type: input
    id: version
    attributes:
      label: Application Version
      description: What version of the application are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS (Apple Silicon)
        - macOS (Intel)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the issue?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste any relevant logs here.
      render: shell
