name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: windows-latest
            rid: win-arm64
          - os: macos-26
            rid: osx-x64
          - os: macos-26
            rid: osx-arm64

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Install workloads
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          dotnet workload restore Nudgly.macOS/Nudgly.macOS.csproj
        elif [ "$RUNNER_OS" == "Windows" ]; then
          dotnet workload restore Nudgly.Windows/Nudgly.Windows.csproj
        fi
      shell: bash

    - name: Restore dependencies
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          dotnet restore Nudgly.macOS/Nudgly.macOS.csproj
        elif [ "$RUNNER_OS" == "Windows" ]; then
          dotnet restore Nudgly.Windows/Nudgly.Windows.csproj
        fi
      shell: bash

    - name: Publish
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          PROJECT="Nudgly.macOS/Nudgly.macOS.csproj"
          EXTENSION=""
        elif [ "$RUNNER_OS" == "Windows" ]; then
          PROJECT="Nudgly.Windows/Nudgly.Windows.csproj"
          EXTENSION=".exe"
        fi

        # Publish to a temporary directory
        dotnet publish $PROJECT --configuration Release --runtime ${{ matrix.rid }} -p:PublishAot=true -p:StripSymbols=true -o ./publish

        # Move and rename the binary to include the RID
        mv ./publish/Nudgly$EXTENSION ./Nudgly-${{ matrix.rid }}$EXTENSION
      shell: bash

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          EXTENSION=""
        else
          EXTENSION=".exe"
        fi
        gh release upload ${{ github.event.release.tag_name }} ./Nudgly-${{ matrix.rid }}$EXTENSION --clobber
      shell: bash
