name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: macos-26
            rid: osx-x64
          - os: macos-26
            rid: osx-arm64

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Install workloads
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          dotnet workload restore Nudgly.macOS/Nudgly.macOS.csproj
        elif [ "$RUNNER_OS" == "Windows" ]; then
          dotnet workload restore Nudgly.Windows/Nudgly.Windows.csproj
        fi
      shell: bash

    - name: Restore dependencies
      run: dotnet restore Nudgly.slnx

    - name: Publish
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          PROJECT="Nudgly.macOS/Nudgly.macOS.csproj"
        elif [ "$RUNNER_OS" == "Windows" ]; then
          PROJECT="Nudgly.Windows/Nudgly.Windows.csproj"
        fi
        dotnet publish $PROJECT --configuration Release --runtime ${{ matrix.rid }} -p:PublishAot=true -p:StripSymbols=true -o ./publish
      shell: bash

    - name: Zip Release
      shell: bash
      run: |
        cd ./publish
        zip -r ../Nudgly-${{ matrix.rid }}.zip ./*

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ github.event.release.tag_name }} Nudgly-${{ matrix.rid }}.zip
